version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - nilerr
    - errorlint
formatters:
  enable:
    - gofmt
    - goimports
issues:
  exclude-generated-files: true
