version: 2
project_name: cnap

before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run ./cmd/cnap completion bash > completions/cnap.bash"
    - sh -c "go run ./cmd/cnap completion zsh > completions/cnap.zsh"
    - sh -c "go run ./cmd/cnap completion fish > completions/cnap.fish"

builds:
  - main: ./cmd/cnap/
    binary: cnap
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/cnap-tech/cli/internal/cmd.version={{.Version}}
      - -X github.com/cnap-tech/cli/internal/cmd.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

brews:
  - skip_upload: "{{ if .Env.HOMEBREW_TAP_TOKEN }}false{{ else }}true{{ end }}"
    repository:
      owner: cnap-tech
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://docs.cnap.tech/cli
    description: CLI for managing CNAP workspaces, clusters, and deployments
    install: |
      bin.install "cnap"
      bash_completion.install "completions/cnap.bash" => "cnap"
      zsh_completion.install "completions/cnap.zsh" => "_cnap"
      fish_completion.install "completions/cnap.fish"
    test: |
      assert_match version.to_s, shell_output("#{bin}/cnap --version")

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: cnap-tech
    name: cli
