version: "3"

set: [errexit, pipefail]

tasks:
  build:
    desc: Build the CLI binary
    cmds:
      - go build -o cnap ./cmd/cnap/

  generate:
    desc: Regenerate API client from OpenAPI spec
    cmds:
      - go tool oapi-codegen -config internal/api/oapi-codegen.yaml internal/api/openapi.json

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format code
    cmds:
      - golangci-lint fmt

  test:
    desc: Run tests
    cmds:
      - go test ./...

  check:
    desc: Run all checks (vet + lint + test)
    cmds:
      - task: vet
      - task: lint
      - task: test

  release:snapshot:
    desc: Build a snapshot release locally (no publish)
    cmds:
      - goreleaser release --snapshot --clean

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f cnap
      - rm -rf dist/
