// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for KaasInfoStatus.
const (
	DEGRADED     KaasInfoStatus = "DEGRADED"
	DELETING     KaasInfoStatus = "DELETING"
	ERROR        KaasInfoStatus = "ERROR"
	PROVISIONING KaasInfoStatus = "PROVISIONING"
	RECONCILING  KaasInfoStatus = "RECONCILING"
	RUNNING      KaasInfoStatus = "RUNNING"
)

// ApiToken defines model for ApiToken.
type ApiToken struct {
	// CreatedAt Unix timestamp (ms)
	CreatedAt float32 `json:"createdAt"`

	// ExpiresAt Unix timestamp (ms), null if never
	ExpiresAt *float32 `json:"expiresAt"`
	Id        string   `json:"id"`

	// LastUsedAt Unix timestamp (ms) of last use
	LastUsedAt *float32 `json:"lastUsedAt"`
	Name       string   `json:"name"`
	Prefix     string   `json:"prefix"`
}

// Cluster defines model for Cluster.
type Cluster struct {
	// CreatedAt Unix timestamp (ms)
	CreatedAt float32 `json:"createdAt"`
	Id        string  `json:"id"`

	// Kaas Present if cluster is KaaS-managed
	Kaas        *KaasInfo `json:"kaas"`
	Name        string    `json:"name"`
	RegionId    string    `json:"regionId"`
	WorkspaceId string    `json:"workspaceId"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	Id   string `json:"id"`
	Name string `json:"name"`

	// Token The full token. This is shown only once — store it securely.
	Token string `json:"token"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code       string      `json:"code"`
		Details    interface{} `json:"details"`
		Message    string      `json:"message"`
		Suggestion *string     `json:"suggestion,omitempty"`
	} `json:"error"`
}

// KaasInfo Present if cluster is KaaS-managed
type KaasInfo struct {
	Namespace     string         `json:"namespace"`
	Status        KaasInfoStatus `json:"status"`
	StatusMessage *string        `json:"statusMessage"`
	Version       string         `json:"version"`
}

// KaasInfoStatus defines model for KaasInfo.Status.
type KaasInfoStatus string

// Workspace defines model for Workspace.
type Workspace struct {
	// CreatedAt Unix timestamp (ms)
	CreatedAt float32 `json:"createdAt"`
	Icon      *string `json:"icon"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`
}

// PatchV1ClustersIdJSONBody defines parameters for PatchV1ClustersId.
type PatchV1ClustersIdJSONBody struct {
	Name *string `json:"name,omitempty"`

	// RegionId Region ID
	RegionId *string `json:"regionId,omitempty"`
}

// PostV1UserTokensJSONBody defines parameters for PostV1UserTokens.
type PostV1UserTokensJSONBody struct {
	// ExpiresInDays Token expiry in days. Omit for no expiry.
	ExpiresInDays *int `json:"expiresInDays,omitempty"`

	// Name Human-readable name for the token
	Name string `json:"name"`
}

// PatchV1ClustersIdJSONRequestBody defines body for PatchV1ClustersId for application/json ContentType.
type PatchV1ClustersIdJSONRequestBody PatchV1ClustersIdJSONBody

// PostV1UserTokensJSONRequestBody defines body for PostV1UserTokens for application/json ContentType.
type PostV1UserTokensJSONRequestBody PostV1UserTokensJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetV1Clusters request
	GetV1Clusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1ClustersId request
	DeleteV1ClustersId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1ClustersId request
	GetV1ClustersId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchV1ClustersIdWithBody request with any body
	PatchV1ClustersIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchV1ClustersId(ctx context.Context, id string, body PatchV1ClustersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1UserTokens request
	GetV1UserTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostV1UserTokensWithBody request with any body
	PostV1UserTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostV1UserTokens(ctx context.Context, body PostV1UserTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteV1UserTokensId request
	DeleteV1UserTokensId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1Workspaces request
	GetV1Workspaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1WorkspacesId request
	GetV1WorkspacesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetV1Clusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ClustersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1ClustersId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1ClustersIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1ClustersId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1ClustersIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchV1ClustersIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchV1ClustersIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchV1ClustersId(ctx context.Context, id string, body PatchV1ClustersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchV1ClustersIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1UserTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1UserTokensRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1UserTokensWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1UserTokensRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostV1UserTokens(ctx context.Context, body PostV1UserTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostV1UserTokensRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteV1UserTokensId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteV1UserTokensIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1Workspaces(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WorkspacesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1WorkspacesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1WorkspacesIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetV1ClustersRequest generates requests for GetV1Clusters
func NewGetV1ClustersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteV1ClustersIdRequest generates requests for DeleteV1ClustersId
func NewDeleteV1ClustersIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1ClustersIdRequest generates requests for GetV1ClustersId
func NewGetV1ClustersIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchV1ClustersIdRequest calls the generic PatchV1ClustersId builder with application/json body
func NewPatchV1ClustersIdRequest(server string, id string, body PatchV1ClustersIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchV1ClustersIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPatchV1ClustersIdRequestWithBody generates requests for PatchV1ClustersId with any type of body
func NewPatchV1ClustersIdRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetV1UserTokensRequest generates requests for GetV1UserTokens
func NewGetV1UserTokensRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/user/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostV1UserTokensRequest calls the generic PostV1UserTokens builder with application/json body
func NewPostV1UserTokensRequest(server string, body PostV1UserTokensJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostV1UserTokensRequestWithBody(server, "application/json", bodyReader)
}

// NewPostV1UserTokensRequestWithBody generates requests for PostV1UserTokens with any type of body
func NewPostV1UserTokensRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/user/tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteV1UserTokensIdRequest generates requests for DeleteV1UserTokensId
func NewDeleteV1UserTokensIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/user/tokens/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1WorkspacesRequest generates requests for GetV1Workspaces
func NewGetV1WorkspacesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workspaces")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetV1WorkspacesIdRequest generates requests for GetV1WorkspacesId
func NewGetV1WorkspacesIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/workspaces/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetV1ClustersWithResponse request
	GetV1ClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ClustersResponse, error)

	// DeleteV1ClustersIdWithResponse request
	DeleteV1ClustersIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteV1ClustersIdResponse, error)

	// GetV1ClustersIdWithResponse request
	GetV1ClustersIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1ClustersIdResponse, error)

	// PatchV1ClustersIdWithBodyWithResponse request with any body
	PatchV1ClustersIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchV1ClustersIdResponse, error)

	PatchV1ClustersIdWithResponse(ctx context.Context, id string, body PatchV1ClustersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchV1ClustersIdResponse, error)

	// GetV1UserTokensWithResponse request
	GetV1UserTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1UserTokensResponse, error)

	// PostV1UserTokensWithBodyWithResponse request with any body
	PostV1UserTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1UserTokensResponse, error)

	PostV1UserTokensWithResponse(ctx context.Context, body PostV1UserTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1UserTokensResponse, error)

	// DeleteV1UserTokensIdWithResponse request
	DeleteV1UserTokensIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteV1UserTokensIdResponse, error)

	// GetV1WorkspacesWithResponse request
	GetV1WorkspacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WorkspacesResponse, error)

	// GetV1WorkspacesIdWithResponse request
	GetV1WorkspacesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1WorkspacesIdResponse, error)
}

type GetV1ClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Cluster `json:"data"`
	}
	JSON401 *Error
	JSON403 *Error
}

// Status returns HTTPResponse.Status
func (r GetV1ClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1ClustersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Error
	JSON403      *Error
	JSON404      *Error
	JSON409      *Error
}

// Status returns HTTPResponse.Status
func (r DeleteV1ClustersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1ClustersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1ClustersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data Cluster `json:"data"`
	}
	JSON401 *Error
	JSON403 *Error
	JSON404 *Error
}

// Status returns HTTPResponse.Status
func (r GetV1ClustersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1ClustersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchV1ClustersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data Cluster `json:"data"`
	}
	JSON401 *Error
	JSON403 *Error
	JSON404 *Error
	JSON422 *Error
}

// Status returns HTTPResponse.Status
func (r PatchV1ClustersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchV1ClustersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1UserTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []ApiToken `json:"data"`
	}
	JSON401 *Error
}

// Status returns HTTPResponse.Status
func (r GetV1UserTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1UserTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostV1UserTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Data CreatedToken `json:"data"`
	}
	JSON401 *Error
}

// Status returns HTTPResponse.Status
func (r PostV1UserTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostV1UserTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteV1UserTokensIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r DeleteV1UserTokensIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteV1UserTokensIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1WorkspacesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Workspace `json:"data"`
	}
	JSON401 *Error
}

// Status returns HTTPResponse.Status
func (r GetV1WorkspacesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WorkspacesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1WorkspacesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data Workspace `json:"data"`
	}
	JSON401 *Error
	JSON403 *Error
	JSON404 *Error
}

// Status returns HTTPResponse.Status
func (r GetV1WorkspacesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1WorkspacesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetV1ClustersWithResponse request returning *GetV1ClustersResponse
func (c *ClientWithResponses) GetV1ClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1ClustersResponse, error) {
	rsp, err := c.GetV1Clusters(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ClustersResponse(rsp)
}

// DeleteV1ClustersIdWithResponse request returning *DeleteV1ClustersIdResponse
func (c *ClientWithResponses) DeleteV1ClustersIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteV1ClustersIdResponse, error) {
	rsp, err := c.DeleteV1ClustersId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1ClustersIdResponse(rsp)
}

// GetV1ClustersIdWithResponse request returning *GetV1ClustersIdResponse
func (c *ClientWithResponses) GetV1ClustersIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1ClustersIdResponse, error) {
	rsp, err := c.GetV1ClustersId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1ClustersIdResponse(rsp)
}

// PatchV1ClustersIdWithBodyWithResponse request with arbitrary body returning *PatchV1ClustersIdResponse
func (c *ClientWithResponses) PatchV1ClustersIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchV1ClustersIdResponse, error) {
	rsp, err := c.PatchV1ClustersIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchV1ClustersIdResponse(rsp)
}

func (c *ClientWithResponses) PatchV1ClustersIdWithResponse(ctx context.Context, id string, body PatchV1ClustersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchV1ClustersIdResponse, error) {
	rsp, err := c.PatchV1ClustersId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchV1ClustersIdResponse(rsp)
}

// GetV1UserTokensWithResponse request returning *GetV1UserTokensResponse
func (c *ClientWithResponses) GetV1UserTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1UserTokensResponse, error) {
	rsp, err := c.GetV1UserTokens(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1UserTokensResponse(rsp)
}

// PostV1UserTokensWithBodyWithResponse request with arbitrary body returning *PostV1UserTokensResponse
func (c *ClientWithResponses) PostV1UserTokensWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostV1UserTokensResponse, error) {
	rsp, err := c.PostV1UserTokensWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1UserTokensResponse(rsp)
}

func (c *ClientWithResponses) PostV1UserTokensWithResponse(ctx context.Context, body PostV1UserTokensJSONRequestBody, reqEditors ...RequestEditorFn) (*PostV1UserTokensResponse, error) {
	rsp, err := c.PostV1UserTokens(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostV1UserTokensResponse(rsp)
}

// DeleteV1UserTokensIdWithResponse request returning *DeleteV1UserTokensIdResponse
func (c *ClientWithResponses) DeleteV1UserTokensIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteV1UserTokensIdResponse, error) {
	rsp, err := c.DeleteV1UserTokensId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteV1UserTokensIdResponse(rsp)
}

// GetV1WorkspacesWithResponse request returning *GetV1WorkspacesResponse
func (c *ClientWithResponses) GetV1WorkspacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetV1WorkspacesResponse, error) {
	rsp, err := c.GetV1Workspaces(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WorkspacesResponse(rsp)
}

// GetV1WorkspacesIdWithResponse request returning *GetV1WorkspacesIdResponse
func (c *ClientWithResponses) GetV1WorkspacesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetV1WorkspacesIdResponse, error) {
	rsp, err := c.GetV1WorkspacesId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1WorkspacesIdResponse(rsp)
}

// ParseGetV1ClustersResponse parses an HTTP response from a GetV1ClustersWithResponse call
func ParseGetV1ClustersResponse(rsp *http.Response) (*GetV1ClustersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ClustersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Cluster `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteV1ClustersIdResponse parses an HTTP response from a DeleteV1ClustersIdWithResponse call
func ParseDeleteV1ClustersIdResponse(rsp *http.Response) (*DeleteV1ClustersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1ClustersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetV1ClustersIdResponse parses an HTTP response from a GetV1ClustersIdWithResponse call
func ParseGetV1ClustersIdResponse(rsp *http.Response) (*GetV1ClustersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1ClustersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data Cluster `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePatchV1ClustersIdResponse parses an HTTP response from a PatchV1ClustersIdWithResponse call
func ParsePatchV1ClustersIdResponse(rsp *http.Response) (*PatchV1ClustersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchV1ClustersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data Cluster `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetV1UserTokensResponse parses an HTTP response from a GetV1UserTokensWithResponse call
func ParseGetV1UserTokensResponse(rsp *http.Response) (*GetV1UserTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1UserTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []ApiToken `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParsePostV1UserTokensResponse parses an HTTP response from a PostV1UserTokensWithResponse call
func ParsePostV1UserTokensResponse(rsp *http.Response) (*PostV1UserTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostV1UserTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Data CreatedToken `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseDeleteV1UserTokensIdResponse parses an HTTP response from a DeleteV1UserTokensIdWithResponse call
func ParseDeleteV1UserTokensIdResponse(rsp *http.Response) (*DeleteV1UserTokensIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteV1UserTokensIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetV1WorkspacesResponse parses an HTTP response from a GetV1WorkspacesWithResponse call
func ParseGetV1WorkspacesResponse(rsp *http.Response) (*GetV1WorkspacesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WorkspacesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Workspace `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetV1WorkspacesIdResponse parses an HTTP response from a GetV1WorkspacesIdWithResponse call
func ParseGetV1WorkspacesIdResponse(rsp *http.Response) (*GetV1WorkspacesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1WorkspacesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data Workspace `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
